spring:
  thymeleaf:
    cache: false # 关闭缓存,默认开启
  datasource:
    url: jdbc:mysql://localhost:3306/order_car?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: "root"
    password: "0218"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.world.ordercar.entity